### PR TITLE
Scala 3 port

### PR DESCRIPTION
**Pull request by bishabosha**
@lihaoyi I have gone with Scala 3.5.0 here since that was the version I have been porting Mill to.

I didn't see any testing procedure - so I used the Mill integration tests to validate the override and scaladoc annotation inference is working. (Also I could remove all the override modifiers I had introduced in my Mill PR)

Note that now I made `moduledefs` a cross module in order to set the right "species" of scala versions to build plugin against. This is probably solved better with Cross2 but that needs to upgrade mill to 0.11.x which breaks the build in other ways I didn't want to touch

```
./millw -i resolve 'moduledefs'._
[1/1] resolve
moduledefs[2.13.14]
moduledefs[3.5.0]
```

```
./millw -i resolve 'moduledefs[2.13.14]'.plugin._
[1/1] resolve
moduledefs[2.13.14].plugin[2.13.0]
moduledefs[2.13.14].plugin[2.13.10]
moduledefs[2.13.14].plugin[2.13.11]
moduledefs[2.13.14].plugin[2.13.12]
moduledefs[2.13.14].plugin[2.13.13]
moduledefs[2.13.14].plugin[2.13.14]
moduledefs[2.13.14].plugin[2.13.1]
moduledefs[2.13.14].plugin[2.13.2]
moduledefs[2.13.14].plugin[2.13.3]
moduledefs[2.13.14].plugin[2.13.4]
moduledefs[2.13.14].plugin[2.13.5]
moduledefs[2.13.14].plugin[2.13.6]
moduledefs[2.13.14].plugin[2.13.7]
moduledefs[2.13.14].plugin[2.13.8]
moduledefs[2.13.14].plugin[2.13.9]
```

```
./millw -i resolve 'moduledefs[3.5.0]'.plugin._
[1/1] resolve
moduledefs[3.5.0].plugin[3.5.0]
```

### CODE REVIEW

**Comment by lihaoyi** [comment]
Sounds good. We do not have standalone tests for this repo AFAIK, so testing indirectly through Mill will have to do. I can tag a release once we merge this

cc @lefou

**Comment by lefou** [comment]
We don't have separate tests. This project makes only sense for Mill and is tested as part of Mills test suites. We just have it standalone to have a Mill-independent lifecycle and be able to publish (older) versions for new Scala compiler versions.

**Comment by lihaoyi** [comment]
@bishabosha I tagged this as 0.11.0-M1, should go out in the next few hours

**Comment by bishabosha** [comment]
@lihaoyi there was some issue in the sonatype publishing task

**Comment by lihaoyi** [comment]
On it. Hopefully https://github.com/com-lihaoyi/mill-moduledefs/commit/ea6c82c0f71d0b1bfede32130eb13a7c507d629c should fix

**Comment by lihaoyi** [comment]
@bishabosha latest run seems to be green https://github.com/com-lihaoyi/mill-moduledefs/actions/runs/10502676571/job/29094764035

**Comment by bishabosha** [comment]
Yep its working, thanks!

**Pull request merged**
